# Generated by Django 2.2.3 on 2019-07-20 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog02', '0002_auto_20190720_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article02',
            name='create_time',
        ),
        migrations.AddField(
            model_name='article02',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='发布时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article02',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article02',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog02.Tags', verbose_name='标签'),
        ),
    ]
